<?php

namespace Database\Seeders;

use App\Models\Products\Product;
use App\Models\Sales\SaleHeader;
use App\Models\Store\ProductInput;
use App\Models\Store\ProductInputHeader;
use App\Models\User;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\PaymentType;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        Product::factory()->createMany([
            ['id' => 1, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي رقم واحد مواليد 66', 'name_en' => ''],
            ['id' => 2, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي رقم 483', 'name_en' => ''],
            ['id' => 3, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي رقم 2 66', 'name_en' => ''],
            ['id' => 4, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيبي جوي عائلي عبوه 44 رقم 4', 'name_en' => ''],
            ['id' => 5, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي مواليد رقم 1 44', 'name_en' => ''],
            ['id' => 6, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي رقم 702', 'name_en' => ''],
            ['id' => 7, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي رقم 603', 'name_en' => ''],
            ['id' => 8, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كونفي رقم 4 50', 'name_en' => ''],
            ['id' => 9, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'مناديل مبلله دادي عبوه 72', 'name_en' => ''],
            ['id' => 10, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'مناديل مبلله زين عبوه 120 حبه', 'name_en' => ''],
            ['id' => 11, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاين قل عايلي 1300 الاصفر', 'name_en' => ''],
            ['id' => 12, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب فرانس ليه رقم 1', 'name_en' => ''],
            ['id' => 13, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب فرانس ليه رقم 2', 'name_en' => ''],
            ['id' => 14, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب رجلاك رقم 1', 'name_en' => ''],
            ['id' => 15, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب رجلاك رقم 2', 'name_en' => ''],
            ['id' => 16, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب رجلاك رقم 3', 'name_en' => ''],
            ['id' => 17, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حليب فرانس ليه رقم 3', 'name_en' => ''],
            ['id' => 18, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رز مصری غذام', 'name_en' => ''],
            ['id' => 19, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بسكويت بسكي اطفال .', 'name_en' => ''],
            ['id' => 20, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرلاك غذاء مبكت منوع.', 'name_en' => ''],
            ['id' => 21, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اعواد اذان خشب 100', 'name_en' => ''],
            ['id' => 22, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اعواد اذن خشب صيني 200 حبه خليل كبير', 'name_en' => ''],
            ['id' => 23, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'معجون دابر بالأعشاب مع الفرشاة', 'name_en' => ''],
            ['id' => 24, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سجنال معجون وسط الاصلي', 'name_en' => ''],
            ['id' => 25, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'معجون سجنال صغير اصلي', 'name_en' => ''],
            ['id' => 26, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'معجون سجنال كبير سعودي 125 مل', 'name_en' => ''],
            ['id' => 27, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فرش استان سبتادینت', 'name_en' => ''],
            ['id' => 28, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فرش اسنان سيلكون الأصلي دكتور', 'name_en' => ''],
            ['id' => 29, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فرش اطفال اورنج ابو غطا', 'name_en' => ''],
            ['id' => 30, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون جونسون اطفال جديد', 'name_en' => ''],
            ['id' => 31, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون مينا بابايا', 'name_en' => ''],
            ['id' => 32, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون ديتول كبير اصلي', 'name_en' => ''],
            ['id' => 33, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون لوكس صغير', 'name_en' => ''],
            ['id' => 34, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون لايفبوي سعودي صغير', 'name_en' => ''],
            ['id' => 35, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صابون دوف صغير المالي', 'name_en' => ''],
            ['id' => 36, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رضاعات الامير كبير', 'name_en' => ''],
            ['id' => 37, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رضاعات مواليد الأمير 60 ملي', 'name_en' => ''],
            ['id' => 38, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رضاعات بتاتو وسط معتم 150 مل', 'name_en' => ''],
            ['id' => 39, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت الزيتون المروى', 'name_en' => ''],
            ['id' => 40, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت الزيتون ليدي بلاص 175 مل', 'name_en' => ''],
            ['id' => 41, 'unit_price' => 0, 'barcode' => '', 'name_ar' => '- زيت جونسون اطفال الاصلي 200 مل', 'name_en' => ''],
            ['id' => 42, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت اطفال بيدا 200 مل', 'name_en' => ''],
            ['id' => 43, 'unit_price' => 0, 'barcode' => '', 'name_ar' => '- زيت نونو 200 مل', 'name_en' => ''],
            ['id' => 44, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر 400 جرام مع شامبو 100 مل دعايه', 'name_en' => ''],
            ['id' => 45, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر صغير شامبو دعايه 50 مل', 'name_en' => ''],
            ['id' => 46, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر كبير 600 مع شامبو 100 مل دعايه', 'name_en' => ''],
            ['id' => 47, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بودره كوبر وسط 200 مع شامبو 50 مل دعايه', 'name_en' => ''],
            ['id' => 48, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شحم كوبرا 180 جرام وسط', 'name_en' => ''],
            ['id' => 49, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حفاضات لاكي بالغين كبير 30 حبة', 'name_en' => ''],
            ['id' => 50, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'حفاضات لاكي بالغين وسط 30 حبة', 'name_en' => ''],
            ['id' => 51, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شحم كوبرا 180 جرام وسط', 'name_en' => ''],
            ['id' => 52, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شحم كوبر صغير جدا 45 جرام', 'name_en' => ''],
            ['id' => 53, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت فاتيكا منوع صغير', 'name_en' => ''],
            ['id' => 54, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زيت فاتيكا منوع كبير', 'name_en' => ''],
            ['id' => 55, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شامبو اطفال بيبي شوف 100 ملي', 'name_en' => ''],
            ['id' => 56, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شامبو اطفال بيبي شوف 200 ملي', 'name_en' => ''],
            ['id' => 57, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شامبو اطفال بيبي شوف 800 ملى -', 'name_en' => ''],
            ['id' => 58, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نيقياء ألماني كبير 250 جرام', 'name_en' => ''],
            ['id' => 59, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نيفياء ألماني وسط', 'name_en' => ''],
            ['id' => 60, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كريم جليسوليد كبير', 'name_en' => ''],
            ['id' => 61, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'گریم جليسوليد وسط', 'name_en' => ''],
            ['id' => 62, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كريم جليسوليد صغير مع الاضافة', 'name_en' => ''],
            ['id' => 63, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصقة عمليات 55 عبوة 50 سران', 'name_en' => ''],
            ['id' => 64, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات 2010 عبوه 25', 'name_en' => ''],
            ['id' => 65, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات تايجر 2510', 'name_en' => ''],
            ['id' => 66, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'غذاء ريرى بدون مرتجع', 'name_en' => ''],
            ['id' => 67, 'unit_price' => 1500, 'barcode' => '9501101272248', 'name_ar' => 'اوجمين شراب ۲۲۸ ملجم الدوانية الحديثة', 'name_en' => ''],
            ['id' => 68, 'unit_price' => 1100, 'barcode' => '9501101270138', 'name_ar' => 'موكسالين ٢٥٠ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 69, 'unit_price' => 1400, 'barcode' => '9501101270190', 'name_ar' => 'او جمين ١٥٦ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 70, 'unit_price' => 1800, 'barcode' => '9501101270206', 'name_ar' => 'اوجمين ۳۱۲ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 71, 'unit_price' => 1900, 'barcode' => '9501101270930', 'name_ar' => 'اوجمين ٤٥٧ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 72, 'unit_price' => 400, 'barcode' => '9501101270619', 'name_ar' => 'قومين ٧٥ اقراص الدوائية الحديثة', 'name_en' => ''],
            ['id' => 73, 'unit_price' => 5000, 'barcode' => '6291100082711', 'name_ar' => 'كبير ميبو مرهم ٣٠ جرام جلفار', 'name_en' => ''],
            ['id' => 74, 'unit_price' => 1000, 'barcode' => '6221094500786', 'name_ar' => 'جوافا شراب ۱۲۰ مل الرشيد سعال', 'name_en' => ''],
            ['id' => 75, 'unit_price' => 500, 'barcode' => '6221088021440', 'name_ar' => 'نيتروماك ريتارد ٢.٥ ملجم ٦٠ك الفتح', 'name_en' => ''],
            ['id' => 76, 'unit_price' => 800, 'barcode' => '6223000012062', 'name_ar' => 'فاركونسيل ١٢٥ ملجم شراب ٨٠ مل فاركو موكسالين', 'name_en' => ''],
            ['id' => 77, 'unit_price' => 900, 'barcode' => '6223000012079', 'name_ar' => 'فاركونسيل ٢٥٠ منجم شراب ٨٠ مل قار کو موكسالين', 'name_en' => ''],
            ['id' => 78, 'unit_price' => 150, 'barcode' => '6221151015307', 'name_ar' => 'فيتامين سي ۱۰۰۰ مل ظروف فاركو فوار سي', 'name_en' => ''],
            ['id' => 79, 'unit_price' => 100, 'barcode' => '6223000011515', 'name_ar' => 'يوريكول فرار ١٢ كيس فاركو', 'name_en' => ''],
            ['id' => 80, 'unit_price' => 600, 'barcode' => '', 'name_ar' => 'اسبرين مغلف ٧٥ ملجم اقراص المحضار اخوان', 'name_en' => 'aspirin 75mg'],
            ['id' => 81, 'unit_price' => 1000, 'barcode' => '540323725902', 'name_ar' => 'سيبرولون ٢٥ ملح أقراص الكتون أمير الدين', 'name_en' => ''],
            ['id' => 82, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => 'كلين انما حقن شرجية كبار العزاني', 'name_en' => 'kleen ename_enma 135ml'],
            ['id' => 83, 'unit_price' => 1400, 'barcode' => '6291109120100', 'name_ar' => 'بندول شراب للرضع بنكة الفراولة المنصوب', 'name_en' => ''],
            ['id' => 84, 'unit_price' => 2200, 'barcode' => '6291109120681', 'name_ar' => 'بندول شراب أزرق للأطفال اليكسير ١٠٠ مل المنصوب', 'name_en' => ''],
            ['id' => 85, 'unit_price' => 300, 'barcode' => '6091403219964', 'name_ar' => 'سولبادين فوار المنصوب', 'name_en' => ''],
            ['id' => 86, 'unit_price' => 900, 'barcode' => '6291109120339', 'name_ar' => 'بندول اكستر - المنصوب وكالة', 'name_en' => ''],
            ['id' => 87, 'unit_price' => 1250, 'barcode' => '5997001359426', 'name_ar' => 'نورمادبين 5 ملجم اقراص بلقيس', 'name_en' => 'normodipiname_en 5mg'],
            ['id' => 88, 'unit_price' => 1650, 'barcode' => '5997001359433', 'name_ar' => 'نورمادبين ١٠ ملم اقراص بلقيس', 'name_en' => ''],
            ['id' => 89, 'unit_price' => 950, 'barcode' => '8901117265158', 'name_ar' => 'اتروليب ١٠ ملجم اقراص ٣٠ ٤ سيبلا', 'name_en' => ''],
            ['id' => 90, 'unit_price' => 1350, 'barcode' => '8901117266049', 'name_ar' => 'اتروليب ۲۰ ملجم اقراص ٣٠ سيبلا', 'name_en' => ''],
            ['id' => 91, 'unit_price' => 2300, 'barcode' => '8901117266018', 'name_ar' => 'اتروليب ٤٠ ملجم اقراص ۱۰ ق سيبلا', 'name_en' => ''],
            ['id' => 92, 'unit_price' => 1100, 'barcode' => '8901117266445', 'name_ar' => 'ديتور ١٠ ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 93, 'unit_price' => 1500, 'barcode' => '8901117265974', 'name_ar' => 'ديتور ۲۰ ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 94, 'unit_price' => 1000, 'barcode' => '8901117268616', 'name_ar' => 'بانتوسيك ٤٠ ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 95, 'unit_price' => 4500, 'barcode' => '8002660033543', 'name_ar' => 'دوفلاك شراب الراقة بدون مرتجع', 'name_en' => ''],
            ['id' => 96, 'unit_price' => 800, 'barcode' => '4031571068980', 'name_ar' => 'نيادي بنك ريتارد ۲۰ ملجم ۱۰۰ الغزالي', 'name_en' => ''],
            ['id' => 97, 'unit_price' => 800, 'barcode' => '9504000288747', 'name_ar' => 'ايبوفلام شراب ۱۰۰ مل كبير شفاكو', 'name_en' => ''],
            ['id' => 98, 'unit_price' => 300, 'barcode' => '9504000269173', 'name_ar' => 'اسبيكوت ٧٥ ملجم اقراص شفاكو أسبرين مختلف', 'name_en' => ''],
            ['id' => 99, 'unit_price' => 1700, 'barcode' => '9504000269340', 'name_ar' => 'كلوفال ٧٥ ملح اقراص ۲۸ قرص شفاكو بلافيكس كلوبي', 'name_en' => ''],
            ['id' => 100, 'unit_price' => 1200, 'barcode' => '9504000288334', 'name_ar' => 'اكسوبان ٤٠ ملجم كبسول ٣٠ ك بانتوبرازول شفاكو', 'name_en' => ''],
            ['id' => 101, 'unit_price' => 50, 'barcode' => '9504000269203', 'name_ar' => 'فولتين دي تي شفاكو ايمفيناك', 'name_en' => ''],
            ['id' => 102, 'unit_price' => 250, 'barcode' => '9504000269692', 'name_ar' => 'امول اقراص صغير شفاكر', 'name_en' => ''],
            ['id' => 103, 'unit_price' => 50, 'barcode' => '9504000269814', 'name_ar' => 'امول اكسترا شريطين اقراص شفاكو', 'name_en' => ''],
            ['id' => 104, 'unit_price' => 100, 'barcode' => '9504000288198', 'name_ar' => 'ميوفيت سي أكياس ۱۰۰۰ ملجم شفاكو فيتامين سي', 'name_en' => ''],
            ['id' => 105, 'unit_price' => 50, 'barcode' => '9504000269265', 'name_ar' => 'او ميتوب ۲۰ ملجم اقراص شفاكو', 'name_en' => ''],
            ['id' => 106, 'unit_price' => 1000, 'barcode' => '6211057011039', 'name_ar' => 'فيتامين سي صافي فوار القادري فيت سي', 'name_en' => ''],
            ['id' => 107, 'unit_price' => 1000, 'barcode' => '6211057021038', 'name_ar' => 'كالسيوم فيتامين سي فوار القادري كالسيفيت', 'name_en' => ''],
            ['id' => 108, 'unit_price' => 200, 'barcode' => '', 'name_ar' => 'سولباقيز فوار رويال سولبادين', 'name_en' => 'solpafizz 65mg'],
            ['id' => 109, 'unit_price' => 750, 'barcode' => '6224000486693', 'name_ar' => 'کولداکت شراب بیوفارم فلوكيت فلودرين', 'name_en' => ''],
            ['id' => 110, 'unit_price' => 50, 'barcode' => '6224000486075', 'name_ar' => 'كولداكت كبسول بيوفارما فلوتاب', 'name_en' => ''],
            ['id' => 111, 'unit_price' => 100, 'barcode' => '6291103730459', 'name_ar' => 'امفيناك دي تي ٥٠ ملجم ك النهدي ديكلوفين', 'name_en' => ''],
            ['id' => 112, 'unit_price' => 450, 'barcode' => '8901040310024', 'name_ar' => 'زبین شراب رنتل الجبر فارما', 'name_en' => ''],
            ['id' => 113, 'unit_price' => 300, 'barcode' => '8901040310031', 'name_ar' => 'زبين ۲۰۰ ملجم زنتل / اقراص الجبر فارما', 'name_en' => ''],
            ['id' => 114, 'unit_price' => 700, 'barcode' => '6221043012971', 'name_ar' => 'ماء سيد شراب الوراقي ماء غريب', 'name_en' => ''],
            ['id' => 115, 'unit_price' => 1500, 'barcode' => '6221025025234', 'name_ar' => 'ابیدون ١٢٥ ملجم شراب أمون القاهرة', 'name_en' => ''],
            ['id' => 116, 'unit_price' => 700, 'barcode' => 'ٍأ-012-01-253', 'name_ar' => 'بيروفين قطر سباء فارما', 'name_en' => ''],
            ['id' => 117, 'unit_price' => 750, 'barcode' => '745604596718', 'name_ar' => 'هستات شراب ١٠٠ مل سباء فارما', 'name_en' => ''],
            ['id' => 118, 'unit_price' => 750, 'barcode' => '745604597227', 'name_ar' => 'موتلين ٦٠ ملجم شراب سباء فارما', 'name_en' => ''],
            ['id' => 119, 'unit_price' => 700, 'barcode' => 'ٍأ-012-03-072', 'name_ar' => 'هكساديل مضمضه ١٠٠ مل سباء فارما', 'name_en' => ''],
            ['id' => 120, 'unit_price' => 1850, 'barcode' => '745604598699', 'name_ar' => 'فالسيترى ٢٦/٢٤ ملجم ٣٠ قرص ساكو بلاص سفرماد', 'name_en' => ''],

            ['id' => 121, 'unit_price' => 1000, 'barcode' => '', 'name_ar' => 'بانتوفكيس بانتوبرازول ٤٠ فيال اميال فارما ', 'name_en' => 'pantofix'],

            ['id' => 122, 'unit_price' => 250, 'barcode' => '745604596725', 'name_ar' => 'هستات اقرص ۲۰ ق سباء فارما', 'name_en' => ''],
            ['id' => 123, 'unit_price' => 700, 'barcode' => '745604597241', 'name_ar' => 'موتلين ٣٠ مل قطر سباء فارما', 'name_en' => ''],
            ['id' => 124, 'unit_price' => 400, 'barcode' => '8904092907648', 'name_ar' => 'يوتابين قيال ١.٢ فيال لاااااااب بعوم', 'name_en' => ''],
            ['id' => 125, 'unit_price' => 1750, 'barcode' => '8941100359600', 'name_ar' => 'جارديان ۱۰ ملج القرص ايمبافت ابن القادري', 'name_en' => ''],
            ['id' => 126, 'unit_price' => 1650, 'barcode' => '8941100359617', 'name_ar' => 'جارديان ٢٥ ملجم اقرص ايمپافنت ابن القادري -', 'name_en' => ''],
            ['id' => 127, 'unit_price' => 1400, 'barcode' => '9501101277120', 'name_ar' => 'ايمبا ١٠ ملجم اقراص العالميه ايمباقنت', 'name_en' => ''],
            ['id' => 128, 'unit_price' => 2100, 'barcode' => '9501101277168', 'name_ar' => 'ايمبا ٢٥ ملجم اقراص العالميه ايمبافنت', 'name_en' => ''],
            ['id' => 129, 'unit_price' => 800, 'barcode' => 'إُ-01-029-11', 'name_ar' => 'أمبروفين فراولة ۱۰۰مل اليمنية المصرية 7', 'name_en' => ''],
            ['id' => 130, 'unit_price' => 1900, 'barcode' => '6251106160158', 'name_ar' => 'لينوبريل ١٠ ملجم اقراص الدولية الاردنية', 'name_en' => ''],
            ['id' => 131, 'unit_price' => 1250, 'barcode' => '6251106160103', 'name_ar' => 'لينوبريل 5ملجم اقراص الدولية الأردنية', 'name_en' => ''],
            ['id' => 132, 'unit_price' => 400, 'barcode' => '8901117266414', 'name_ar' => 'اسبين 100 ملجم اقراص سيبلا', 'name_en' => ''],
            ['id' => 133, 'unit_price' => 50, 'barcode' => '8901117264298', 'name_ar' => 'لوماك ۲۰ منجم كبسول أشرطة سيبلا', 'name_en' => ''],
            ['id' => 134, 'unit_price' => 3200, 'barcode' => '', 'name_ar' => 'ميبو مرهم صغير أبو زيد', 'name_en' => ''],
            ['id' => 135, 'unit_price' => 400, 'barcode' => '6212035090381', 'name_ar' => 'فاديرين 81 ملجم اقراص هيلثي فارما جوسبرين -', 'name_en' => ''],
            ['id' => 136, 'unit_price' => 1300, 'barcode' => '8905887002258', 'name_ar' => 'ابيكسان هيل 5 ملجم اقراص ابيكسا هيلان', 'name_en' => ''],
            ['id' => 137, 'unit_price' => 50, 'barcode' => '8904159404622', 'name_ar' => 'سكو فاست اقراص العابد امفيناك بدون مرتجع', 'name_en' => ''],
            ['id' => 138, 'unit_price' => 800, 'barcode' => '6210236134187', 'name_ar' => 'بوفين شراب ۱۰۰مل الخياط امبروفين شراب', 'name_en' => ''],

            ['id' => 139, 'unit_price' => 4500, 'barcode' => '3664798036558', 'name_ar' => 'بلافيكس ٧٥ ملجم اقراص الصباري -بانتوبرازول ٤٠ فيال اميال فارما بالتوفيكس', 'name_en' => ''],

            ['id' => 140, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موكسالين ١٢٥ ملجم شراب الدوائية الحديثة', 'name_en' => ''],
            ['id' => 141, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'توسكان شراب الجبل', 'name_en' => ''],
            ['id' => 142, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بيستول ۲٫٥ ملغ اقراص الجبل', 'name_en' => ''],
            ['id' => 143, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بیستول ٥ ملغ اقراص عادي الجبل', 'name_en' => ''],
            ['id' => 144, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سوفيكان ٢٠ ملغ اقراص الجبل', 'name_en' => ''],
            ['id' => 145, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سوفيكان ١٠ ملح أقراص الجبل الحكمه', 'name_en' => ''],
            ['id' => 146, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موتيل ١٠٠مل موتلين شراب العالمية', 'name_en' => ''],
            ['id' => 147, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نيولاكس ۱۰۰ مل شراب العالمية لاكسولاك', 'name_en' => ''],
            ['id' => 148, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'هايبين ٥٠٠مل اقراص الجبل أموكسيل ۱۰ ش', 'name_en' => ''],
            ['id' => 149, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بیمناست ۱۰۰۰ ملجم فيال العربية فوربار', 'name_en' => ''],
            ['id' => 150, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زوراكسون ۱۰۰۰ ملجم وريدي الفتح فورسيف', 'name_en' => ''],
            ['id' => 151, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيفوران 1 جرام فيال فارکو اور تاکسیم', 'name_en' => ''],
            ['id' => 152, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'باراسيتامول قرب برفلجان فاركو', 'name_en' => ''],
            ['id' => 153, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اور تکسیم اجرام فيال الجبل', 'name_en' => ''],
            ['id' => 154, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيفتاد ۱۰۰۰ قيال فوربار الجبل', 'name_en' => ''],
            ['id' => 155, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قوربار اجرام فيال سيبلا', 'name_en' => ''],
            ['id' => 156, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'انسولين اتش بيو ار فيال أصفر) سيديكو الحارث', 'name_en' => ''],
            ['id' => 157, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'هيبارين صوديوم ٥٠٠٠ وحدة عبوة 3 أمبولات جديد الحارث', 'name_en' => ''],
            ['id' => 158, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبروفلوكساسين محلول العافية سيبلوكس', 'name_en' => ''],
            ['id' => 159, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ديكساميتازون امبول فلهوم', 'name_en' => ''],
            ['id' => 160, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'زجاج برفلجان قرب زجاج فلهوم', 'name_en' => ''],
            ['id' => 161, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ديكستروز ٤٠% امبول رويال فارما بالحبه الواحده', 'name_en' => ''],
            ['id' => 162, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'براسيتامول مغنيات زجاج رويال بر فلجان رویامول', 'name_en' => ''],
            ['id' => 163, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اقيل امبول رويال فارما', 'name_en' => ''],
            ['id' => 164, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بليمازول امبول رويال فارما ريمو بلازا', 'name_en' => ''],
            ['id' => 165, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بي كومبلكس أمبول رويال فارما', 'name_en' => ''],
            ['id' => 166, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيتامين سي أمبول ٥٠٠ رويال فارما', 'name_en' => ''],
            ['id' => 167, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جنتاميسين أمبول ۸۰ ملجم رويال فارما', 'name_en' => ''],
            ['id' => 168, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'متريندازول قرب جال فارما فلاجيل بدون موصل', 'name_en' => ''],
            ['id' => 169, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'انترابيم قيال مياس 1 جرام سيفبيم قوربار', 'name_en' => ''],
            ['id' => 170, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'باراكونيكا اجرام فيال محلات مياس برفلجان', 'name_en' => ''],
            ['id' => 171, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمبونينت فيال ۲۰ ف أرض الجنتين كومبيفيت', 'name_en' => ''],
            ['id' => 172, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'دوبروس ۲۰۰ مل امبول دوبامين بعوم', 'name_en' => ''],
            ['id' => 173, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'وکیل مختوم تینام ٥٠٠ ملجم بان مبنيم مهدي الشاعر', 'name_en' => ''],
            ['id' => 174, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فانكومايسين اجرام فيال الشاعر فانكولون ۱۰۰۰', 'name_en' => ''],
            ['id' => 175, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ستو بالجيك برفلجان بارستامول مغنية الشاعر', 'name_en' => ''],
            ['id' => 176, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبروفلوكساسين قرب الجيش سيبلوكس سيبروكيد', 'name_en' => ''],
            ['id' => 177, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبلاسيف اجرام فيال سيبلا', 'name_en' => ''],
            ['id' => 178, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيبلاسيف ٥٠٠ ملجم فيال سيبلا', 'name_en' => ''],
            ['id' => 179, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سیلاكيب ٥٠٠ جرام فيال تينام رسام الشاعر', 'name_en' => ''],
            ['id' => 180, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موبيم ا مجم فيال رسام الشاعر میرونیم مورنیم بدون مرتجع', 'name_en' => ''],
            ['id' => 181, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'دايميد ۲۰ منجم امبول الربيعي ديتور ١٠ امبول', 'name_en' => ''],
            ['id' => 182, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سكر مغنيات الجبل', 'name_en' => ''],
            ['id' => 183, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رنجر مغذيات الجبل', 'name_en' => ''],
            ['id' => 184, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فلاجيل قرب مع الموصلات اميال فارما بدون مرتجع', 'name_en' => ''],
            ['id' => 185, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' روها ليفوفلوكساسين قرب ۱۰۰ مل روها فارما معى الموصل ليلوباكت', 'name_en' => ''],
            ['id' => 186, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' روها سيبروفلوكساسين قرب ۱۰۰ مل روها فارما معى الموصل سيبلوكس', 'name_en' => ''],
            ['id' => 187, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' اوندر يسترون امبول ۸ ملجم صادق البرحي ايمست', 'name_en' => ''],
            ['id' => 188, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' سالاتاز ٤٥ فيال الأمل تاركت', 'name_en' => ''],
            ['id' => 189, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' لازكس امبول الصباري', 'name_en' => ''],
            ['id' => 190, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' هيتاسون ۱۰۰ ملجم فيال فارما بيدا هيدروكرتزون', 'name_en' => ''],
            ['id' => 191, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' بروسيوم ١٠ امبول امبولات فارما بيدا مغناسيوم', 'name_en' => ''],
            ['id' => 192, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' سيفتر یاکسون أكوي اجم فيال تعافي فارما سي ون سيبلاسيف', 'name_en' => ''],
            ['id' => 193, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' نازکت کوزمابيتاز ٤,٥ ملجم قرب الجيش تازكت', 'name_en' => ''],
            ['id' => 194, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' كورما تكسي اجرام فيال اور تكسيم سيفوتاكسيم الجيش و', 'name_en' => ''],
            ['id' => 195, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ديتور امبول عبوة ۲۰ امبوله ابوزيد سيبلا ٢٠ أم', 'name_en' => ''],
            ['id' => 196, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ميراكوي اجم فيال تعافي فارما ميرونيم', 'name_en' => ''],
            ['id' => 197, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' افسيناف اجم فيال فانكومايسين تعافي فارما', 'name_en' => ''],
            ['id' => 198, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' اینوکس بارين ٤٠٠٠ و دتعافي فارما ٢ أمبول', 'name_en' => ''],
            ['id' => 199, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' اینو كسبارين ٦٠٠٠ و دتعافي فارما ٢ امبول', 'name_en' => ''],
            ['id' => 200, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' کابرین ۲۵۰۰۰ و.د فيال فارما بيوتك هيبارين', 'name_en' => ''],
            ['id' => 201, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ملح مغنيات القطريفي', 'name_en' => ''],
            ['id' => 202, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' مخلوط مغذيات القطريفي', 'name_en' => ''],
            ['id' => 203, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فانكوبال ۱۰۰۰ ملجم فيال أميال فانكوميسين', 'name_en' => ''],
            ['id' => 204, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' سوكسيبال مغذيات اميال فارما موكساسيب', 'name_en' => ''],
            ['id' => 205, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فير سدرين ٢ ملي أمبول لازكس بريميم ديرين', 'name_en' => ''],
            ['id' => 206, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' درسترون ۲ ملي أمبول ايمست بریمیم دیرین', 'name_en' => ''],
            ['id' => 207, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' ليفيتام ٥٠٠ ملجم فيال كيبرا بیوسنسورس بيواكتف', 'name_en' => ''],
            ['id' => 208, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' فاتكولون ۱۰۰۰ ملجم فيال جلفار', 'name_en' => ''],
            ['id' => 209, 'unit_price' => 0, 'barcode' => '', 'name_ar' => ' روها میترندازول ۱۰۰ ما قرب روها فارما معى الموصل فلاجيل', 'name_en' => ''],
            ['id' => 210, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 16', 'name_en' => ''],
            ['id' => 211, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 14', 'name_en' => ''],
            ['id' => 212, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 12', 'name_en' => ''],
            ['id' => 213, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون ابو 10', 'name_en' => ''],
            ['id' => 214, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 6', 'name_en' => ''],
            ['id' => 215, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قساطر سلكون مقاس 8', 'name_en' => ''],
            ['id' => 216, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قرب بول', 'name_en' => ''],
            ['id' => 217, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شاش معقم 10*10 عبوة 50', 'name_en' => ''],
            ['id' => 218, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلفز معقم ماليزي 7.5', 'name_en' => ''],
            ['id' => 219, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رایز تیوب مقاس 16', 'name_en' => ''],
            ['id' => 220, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رايز تيوب مقاس 14', 'name_en' => ''],
            ['id' => 221, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رایز تیوب مقاس 12', 'name_en' => ''],
            ['id' => 222, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سنتر لاين مقاس 7', 'name_en' => ''],
            ['id' => 223, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سنتر لاين مقاس 3', 'name_en' => ''],
            ['id' => 224, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 50 جرام', 'name_en' => ''],
            ['id' => 225, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رايز تيوب مقاس 8', 'name_en' => ''],
            ['id' => 226, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيدنق تيوب 10', 'name_en' => ''],
            ['id' => 227, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 100 جرام', 'name_en' => ''],
            ['id' => 228, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن 500 جرام', 'name_en' => ''],
            ['id' => 229, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 1000 جرام', 'name_en' => ''],
            ['id' => 230, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'قطن ابو 250', 'name_en' => ''],
            ['id' => 231, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام اكسجين اسمول', 'name_en' => ''],
            ['id' => 232, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام اكسجين مديم', 'name_en' => ''],
            ['id' => 233, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام اكسجين كبار', 'name_en' => ''],
            ['id' => 234, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام نيو بليزر اسمول', 'name_en' => ''],
            ['id' => 235, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام نيو بليزر لارج', 'name_en' => ''],
            ['id' => 236, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر باد صيني عبوة 25', 'name_en' => ''],
            ['id' => 237, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سركت تخدير اطفال', 'name_en' => ''],
            ['id' => 238, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سركت تخدير كبار', 'name_en' => ''],
            ['id' => 239, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'شرکت تخدير ابو فلترين', 'name_en' => ''],
            ['id' => 240, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'مكرو دروب ابو 150', 'name_en' => ''],
            ['id' => 241, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موصلات تقطير', 'name_en' => ''],
            ['id' => 242, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'موصلات قرب دم', 'name_en' => ''],
            ['id' => 243, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سكشن تيوب مقاس 10', 'name_en' => ''],
            ['id' => 244, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج 5 مل', 'name_en' => ''],
            ['id' => 245, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج 20 مل', 'name_en' => ''],
            ['id' => 246, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج 3 مل', 'name_en' => ''],
            ['id' => 247, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج ابو 10', 'name_en' => ''],
            ['id' => 248, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج ابو 50 تغذية', 'name_en' => ''],
            ['id' => 249, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج ابو 50 مل', 'name_en' => ''],
            ['id' => 250, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'خيوط سلك اسباني كتنج مقاس 2.0', 'name_en' => ''],
            ['id' => 251, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كاثيولا 26', 'name_en' => ''],
            ['id' => 252, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كاثيولا مقاس 24 قصير', 'name_en' => ''],
            ['id' => 253, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ثري وي', 'name_en' => ''],
            ['id' => 254, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلفز لاتكس ماليزي مع البودر اسمول', 'name_en' => ''],
            ['id' => 255, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الكترود ECG', 'name_en' => ''],
            ['id' => 256, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الكترود ECG', 'name_en' => ''],
            ['id' => 257, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'کاندم بول L', 'name_en' => ''],
            ['id' => 258, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الصق عجل مقاس 2.51', 'name_en' => ''],
            ['id' => 259, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الصق عجل مقاس 2.53', 'name_en' => ''],
            ['id' => 260, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات 1010 عبوة 25', 'name_en' => ''],
            ['id' => 261, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'لصق عمليات 1510 عبوة 50', 'name_en' => ''],
            ['id' => 262, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'الصق عمليات 3010 عبوة 50', 'name_en' => ''],
            ['id' => 263, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلفز فينال ابيض مقاس مديم M', 'name_en' => ''],
            ['id' => 264, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاین مبلل', 'name_en' => ''],
            ['id' => 265, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاين مبلل كبير', 'name_en' => ''],
            ['id' => 266, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فاین مبلل وسط', 'name_en' => ''],
            ['id' => 267, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رباط ضاغط مقاس 310', 'name_en' => ''],
            ['id' => 268, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رباط ضاغط مقاس 15', 'name_en' => ''],
            ['id' => 269, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'رباط ضاغط مقاس 7.5', 'name_en' => ''],
            ['id' => 270, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'كمام ربل', 'name_en' => ''],
            ['id' => 271, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 2.5', 'name_en' => ''],
            ['id' => 272, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 3.5', 'name_en' => ''],
            ['id' => 273, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 4', 'name_en' => ''],
            ['id' => 274, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 6', 'name_en' => ''],
            ['id' => 275, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اندر تركل تيوب مع الكف 7', 'name_en' => ''],
            ['id' => 276, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيدنق تيوب 6', 'name_en' => ''],
            ['id' => 277, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'فيدنق تيوب 6', 'name_en' => ''],
            ['id' => 278, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سكشن تيوب مقاس 6', 'name_en' => ''],
            ['id' => 279, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سيرنج أبو 1 انسولين', 'name_en' => ''],
            ['id' => 280, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'نازل اكسجين لارج', 'name_en' => ''],
            ['id' => 281, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'علب براز معقم', 'name_en' => ''],
            ['id' => 282, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'ثري وي', 'name_en' => ''],
            ['id' => 283, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بوليميكورت ٥ ملح مل محلول ناتكو', 'name_en' => ''],
            ['id' => 284, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'بوتاسيوم امبول ابو فارع الغيالة', 'name_en' => ''],
            ['id' => 285, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'صوديوم بيكربونات فيال ٥٠مل ابو فارع', 'name_en' => ''],
            ['id' => 286, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'سومازينا امبول ۱۰۰۰ ملح الشرق . امبولات', 'name_en' => ''],
            ['id' => 287, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'جلكونات كالسيوم ١٠ مل امبول رویال فارما', 'name_en' => ''],
            ['id' => 288, 'unit_price' => 0, 'barcode' => '', 'name_ar' => 'اسیست امبول المفضل', 'name_en' => ''],

        ]);
    }
}
